config/routes.rb
Rails.application.routes.draw do
  resources :thecomments
  resources :comments, only: [:create, :destroy, :update]
  resources :articles do
    resources :images, only: [:create, :destroy]
  end
  resources :orders, only: [:new, :create]
  resources :user do
    resources :carts, only: [:index, :create, :destroy]
    resources :avatars, only: [:create, :destroy]
  end
  devise_for :users
  resources :modifications, only: [:update]
  root to: "articles#index"
  get '/old', to: 'static_pages#old_skool_gaming'
  get '/kit', to: 'static_pages#kit_ui'
  get '/cgv', to: 'static_pages#cgv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, length: {maximum: 30, too_long: "%{count} caractère autorisés pour le titre" }, presence: true
  validates :content, length: { maximum: 250,
    too_long: "%{count} caractère autorisés pour la description" }, presence: true
  validates :price, :console, :typeofgame, presence: true
  validates :price, numericality: { message: "%{value} semble incorrect" }

    
    enum :typeofgame, [:Mauvais_état, :Bon_état, :Très_bon_état, :Neuf]
    enum :console, [:SNES, :PS1, :SEGA]
    belongs_to :seller, class_name: "User"
    belongs_to :buyer, class_name: "User", optional: true
    has_many_attached :images
    has_many :article_carts
    has_many :carts, through: :article_carts
    has_many :article_orders
    has_many :orders, through: :article_orders
    has_many :comments, as: :commentable
    has_many :thecomments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @articles = @article.seller.my_articles
    @artcart = ArticleCart.all
    @artcartuser = @artcart.where(article_id: @article.id, cart_id: current_user.cart.id)[0]
    puts @artcartuser.class
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    art = params[:article]
    @article = Article.new(title: art[:title], content: art[:content], price: art[:price], typeofgame: art[:typeofgame], console: art[:console])
    @article.seller = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article créé avec succès" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    @article = Article.find(params[:id])
    @article.update!(title: params[:title]) if params[:title] != ""
    @article.update!(content: params[:description]) if params[:description] != ""
    @article.update!(price: params[:price]) if params[:price] != ""
    redirect_to article_path(@article)
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article supprimé avec succès" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :price)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/form/article/_allarticle.html.erb
<!-- Ne pas afficher l'article si article.buyer est différent de nil (Donc s'il a été acheté) -->
<!-- if article.buyer != nil -->


    <!-- Le code ici a pour but de ne montrer que les articles que l'on recherche grace aux filtres 
          Parameters: {"console"=>"PS1", "typeofgame"=>"Console"}  Ce qui signifie, si aucun filtre n'existe, donc on affiche tout
          else   Si on rentre dans la condition else, cela signifie qu'il y a un filtre, dans ce cas on affiche pas tout -->
      <div class="col-md-6 col-lg-3 pb-5">
      <div class="cardos border border-2 border-dark zoom rounded-0" style="width: 15rem;">
        <div class="fw-bold text-dark">
          <%= article.title %>

        </div>
        
        <% if article.console == "SEGA" && current_user %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/nintendo-nes-console-game-xwVG4NC-600.jpg", size: "200x300"), article_path(article) %>
        <% elsif article.console == "PS1" && current_user %>
        <%= link_to image_tag("https://atlas-content-cdn.pixelsquid.com/assets_v2/193/1936372297870873864/jpeg-600/G03.jpg?modifiedAt=1", size: "200x300"), article_path(article) %>
        <% elsif article.console == "SNES" && current_user %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/super-nintendo-snes-kovW238-600.jpg", size: "200x300"), article_path(article) %>
        <% else %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/nintendo-nes-console-game-xwVG4NC-600.jpg", size: "200x300"), new_user_registration_path %>
        <% end %>
        
  <div class="card-body">
    <h5 class="card-title"></h5>
    <div class="clearfix mb-3">
              <% if article.console == "SEGA" %>
              <span class="float-start badge rounded-pill bg-primary"><%= article.console %></span>
              <% elsif article.console == "SNES" %>
              <span class="float-start badge rounded-pill bg-danger"><%= article.console %></span>
              <% elsif article.console == "PS1" %>
              <span class="float-start badge rounded-pill bg-dark"><%= article.console %></span>
              <% end %>
              <span class="float-end price-hp fw-bold text-dark "><%= article.price %> €</span>
              
            </div>
  </div>
</div>

</div>

app/views/form/article/_comments.html.erb
<div class="container px-4 py-5 card">
  <div class="row">
    <div class="col-2">
      <img
        src="https://cdn-icons-png.flaticon.com/128/1747/1747273.png"
        width="70"
        class="rounded-circle mt-2"
      >
    </div>

    <div class="col-10">
      <div class="comment-box ml-2">
        <h4>ici le content</h4>
        <div class="rating">
          <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
          <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
          <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
          <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
          <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
        </div>
        <div class="comment-area">
          <textarea class="form-control" placeholder="what is your view?" rows="4"></textarea>
        </div>
        <div class="comment-btns mt-2">
          <div class="row">
            <div class="col-6">
              <div class="pull-left">
                <button class="btn btn-success btn-sm">Cancel</button>
              </div>
            </div>
            <div class="col-6">
              <div class="pull-right">
                <button class="btn btn-success send btn-sm">Send
                  <i class="fa fa-long-arrow-right ml-1"></i></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/form/article/_edit.html.erb
<div class="container p-5">
<h1 class="pb-3">Modifier l'article</h1>
  <div class="container bg-white border border-2 border-dark">
<%= form_with url: "/articles/#{params[:id]}", method: :put do |form| %>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= @article.title %>
    <%= form.text_field :title, class:"form-control", placeholder:"Titre" %>
  </div>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= @article.content %>
    <%= form.text_field :description, class:"form-control", placeholder:"Description" %>
  </div>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= @article.price %>
    <%= form.text_field :price, class:"form-control", placeholder:"Prix" %>
  </div>

  <div class=" text-center">
    <%= form.submit 'Mettre à jour', :class => 'btn btn-primary rounded-0' %>
  </div>
<% end %>
</div>
</div>

app/views/form/article/_example.html.erb
<section class="bg-mainos">
  <div class="container ">
    <div class="row ">
      <p class="lead text-dark pt-5">Nouveaux articles</p>

      <div class="d-flex flex-lg-row flex-column">
        <% articles.where(buyer: nil).last(4).each do |article| %>
          <div
            class="cardos border border-2 border-dark zoom rounded-0 mb-5"
            style="width: 15rem;"
          >
            <div class="text-dark">
              <p class="fw-bold"><%= article.title %></p>
            </div>
            
            <% if article.console == "SEGA" && current_user %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/nintendo-nes-console-game-xwVG4NC-600.jpg", size: "200x300"), article_path(article) %>
        <% elsif article.console == "PS1" && current_user %>
        <%= link_to image_tag("https://atlas-content-cdn.pixelsquid.com/assets_v2/193/1936372297870873864/jpeg-600/G03.jpg?modifiedAt=1", size: "200x300"), article_path(article) %>
        <% elsif article.console == "SNES" && current_user %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/super-nintendo-snes-kovW238-600.jpg", size: "200x300"), article_path(article) %>
        <% end %>
            <div class="card-body">
              <h5 class="card-title"></h5>
              <div class="clearfix mb-3">
                <% if article.console == "SEGA" %>
              <span class="float-start badge rounded-pill bg-primary"><%= article.console %></span>
              <% elsif article.console == "SNES" %>
              <span class="float-start badge rounded-pill bg-danger"><%= article.console %></span>
              <% elsif article.console == "PS1" %>
              <span class="float-start badge rounded-pill bg-dark"><%= article.console %></span>
              <% end %>
              <span class="float-end price-hp fw-bold text-dark "><%= article.price %> €</span>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/form/article/_exampleform.html.erb
<div
    class="cardos border border-2 border-dark zoom rounded-0 mb-5"
    style="width: 15rem;"
>
    <div class="fw-bold text-dark">
        <p class="fw-bold"><%= article.title %></p>
    </div>
    <% if article.console == "SEGA" && current_user %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/nintendo-nes-console-game-xwVG4NC-600.jpg", size: "200x300"), article_path(article) %>
        <% elsif article.console == "PS1" && current_user %>
        <%= link_to image_tag("https://atlas-content-cdn.pixelsquid.com/assets_v2/193/1936372297870873864/jpeg-600/G03.jpg?modifiedAt=1", size: "200x300"), article_path(article) %>
        <% elsif article.console == "SNES" && current_user %>
        <%= link_to image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/super-nintendo-snes-kovW238-600.jpg", size: "200x300"), article_path(article) %>
        <% end %>
    <div class="card-body">
        <h5 class="card-title"></h5>
            <div class="clearfix mb-3">
                <% if article.console == "SEGA" %>
              <span class="float-start badge rounded-pill bg-primary"><%= article.console %></span>
              <% elsif article.console == "SNES" %>
              <span class="float-start badge rounded-pill bg-danger"><%= article.console %></span>
              <% elsif article.console == "PS1" %>
              <span class="float-start badge rounded-pill bg-dark"><%= article.console %></span>
              <% end %>
              <span class="float-end price-hp fw-bold text-dark "><%= article.price %> €</span>
            </div>
    </div>
</div>

app/views/form/article/_new.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %>
        prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="bg-white container pt-5 pb-2 border border-2 border-dark card-box">
  <div class="col-4 mx-auto py-3 px-5 mb-4 bg-white border border-2 border-dark">
    <%= form.label :"Titre de l'annonce", style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="col-4 mx-auto py-3 px-5 mb-4 bg-white border border-2 border-dark">
    <%= form.label :"Description de l'article", style: "display: block" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="col-4 mx-auto py-3 px-5 mb-4 bg-white border border-2 border-dark">
    <%= form.label :Prix, style: "display: block" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="col-4 mx-auto py-3 px-5 mb-4 bg-white border border-2 border-dark">
    <%= form.label :"Choisissez une catégorie" %><br>
    <%= form.select :typeofgame, options_for_select(Article.typeofgames.map {|key, value| [key.titleize, Article.typeofgames.key(value)]}, article.typeofgame) %>
  </div>

  <div class="col-4 mx-auto py-3 px-5 mb-4 bg-white border border-2 border-dark">
    <%= form.label :"Modèle de Console" %><br>
    <%= form.select :console, options_for_select(Article.consoles.map {|key, value| [key.titleize, Article.consoles.key(value)]}, article.console) %>
  </div>

  <div class="col-4 mx-auto py-3 px-5 mb-4">
    <%= form.submit "Création article", class:"btn bg-gradient-primary rounded-0 w-100" %>
  </div>
<% end %>
</div>

app/views/form/article/_newcom.html.erb
<%= form_with url: "/comments", method: :post do |form| %>

  <%= hidden_field_tag :article_id, params[:id] %>
  <%= hidden_field_tag :commentable_id, params[:id] %>
  <%= hidden_field_tag :commentable_type, "Article" %>

  <h6><%= form.label :title, "Titre du commentaire" %></h6>
  <%= form.text_field :title %><br>

  <h6><%= form.label :content, "Commentaire" %></h6>
  <%= form.text_area :content %>
  <br>
  <%= form.submit "Envoyer" %>
<% end %>

app/views/form/article/_show.html.erb
<% if current_user == @article.seller %>
<section class="bg-mainos">
  <div class="container pt-5 pb-5">
    <div class="card">
      <div class="card-body rounded-0 border border-2 border-dark card-box">
        <p class="lead text-dark">Ajoute des photos</P>
          <div class="d-flex justify-content-between text-center align-items-center">
            <%= form_tag article_images_path(@article), multipart: true do %>
      <%= file_field_tag :images, class:"btn btn-outline-dark border-2 rounded-0" %>
      <%= submit_tag "Valider la photo", class:"btn btn-primary rounded-0" %>
    <% end %>
        
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

<div class="container px-4 py-5" id="featured-3">
    <div class="row center">

    <% if @article.images.attached? %>
        <% i = 0 %> <!-- Ce sera l'ID de l'image dans le tableau d'image -->

        <% @article.images.each do |image|%>
        <div class="col-lg-6 col-md-6"> 
            <div class="col">    
                <%= image_tag image, alt: 'avatar', class: "img-fluid border border-2 border-dark bg-white img" %> 
            </div>
        <div class="col">  
        <% if @article.seller == current_user %>
          <%= button_to "Supprimer la photo", article_image_path(@article.id, image.id, task_id: i), method: :delete, class:"btn btn-outline-dark border-2 rounded-0" %>
        <% end %>
            <% i = i + 1 %>
        </div> 
      </div>
    <% end %> 
    </div>
</div>    


        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/form/article/_undershow.html.erb
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %>
  |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>