config/routes.rb
Rails.application.routes.draw do
  resources :thecomments
  resources :comments, only: [:create, :destroy, :update]
  resources :articles do
    resources :images, only: [:create, :destroy]
  end
  resources :orders, only: [:new, :create]
  resources :user do
    resources :carts, only: [:index, :create, :destroy]
    resources :avatars, only: [:create, :destroy]
  end
  devise_for :users
  resources :modifications, only: [:update]
  root to: "articles#index"
  get '/old', to: 'static_pages#old_skool_gaming'
  get '/kit', to: 'static_pages#kit_ui'
  get '/cgv', to: 'static_pages#cgv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, length: {maximum: 30, too_long: "%{count} caractère autorisés pour le titre" }, presence: true
  validates :content, length: { maximum: 250,
    too_long: "%{count} caractère autorisés pour la description" }, presence: true
  validates :price, :console, :typeofgame, presence: true
  validates :price, numericality: { message: "%{value} semble incorrect" }

    
    enum :typeofgame, [:Mauvais_état, :Bon_état, :Très_bon_état, :Neuf]
    enum :console, [:SNES, :PS1, :SEGA]
    belongs_to :seller, class_name: "User"
    belongs_to :buyer, class_name: "User", optional: true
    has_many_attached :images
    has_many :article_carts
    has_many :carts, through: :article_carts
    has_many :article_orders
    has_many :orders, through: :article_orders
    has_many :comments, as: :commentable
    has_many :thecomments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @articles = @article.seller.my_articles
    @artcart = ArticleCart.all
    @artcartuser = @artcart.where(article_id: @article.id, cart_id: current_user.cart.id)[0]
    puts @artcartuser.class
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    art = params[:article]
    @article = Article.new(title: art[:title], content: art[:content], price: art[:price], typeofgame: art[:typeofgame], console: art[:console])
    @article.seller = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article créé avec succès" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    @article = Article.find(params[:id])
    @article.update!(title: params[:title]) if params[:title] != ""
    @article.update!(content: params[:description]) if params[:description] != ""
    @article.update!(price: params[:price]) if params[:price] != ""
    redirect_to article_path(@article)
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article supprimé avec succès" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :price)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<section class="pb-5 pt-5 bg-mainos2">


<%= render "form/article/edit", article: @article %>

<br>
<% if flash[:error] %>
  <div class="notice", style="color: red"><%= flash[:error] %></div>
<% end %>
</section>

app/views/articles/index.html.erb
<% if flash[:error] %>
  <div class="notice", style="color: red"><%= flash[:error] %></div>
<% end %>

<% if current_user.nil? %>
<%= render "form/header/header" %>
<% elsif current_user %>
<section class="bg-mainos">
  <div class="container pt-5 pb-5">
    <div class="card">
      <div class="card-body rounded-0 border border-2 border-dark card-box">
        <p class="lead text-dark">Besoin d'astuces ?</P>
          <div class="d-flex flex-column flex-lg-row justify-content-between text-center align-items-center">
        <p>Pensez à ajouter un avatar sur votre profil pour gagner en visibilité.</p>
        <%= link_to "Personnaliser", user_path(current_user), class: "btn btn-lg btn-primary rounded-0" %>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

<% if current_user %>
<%= render partial: "form/article/example", locals: { articles: @articles } %>
<% end %>

      <!-- Partie filtre -->
      <% if current_user.nil? %>
      <section class="bg-white pt-5 border-bottom border-2 border-dark">
        <% else %>
        <section class="bg-mainos pt-5 ">
          <% end %>
      <div class="container d-flex justify-content-center align-items-end">
          <div class="card mb-5">
            <div class="card-body rounded-0 border border-2 border-dark card-box">
          <p class="lead text-dark ombre"> Quel type de console recherchez-vous ?</p>
        <%= form_with url: "/articles", method: :get do |form| %>
            <p>Type de console</p>
            <%= form.select :console, options_for_select(Article.consoles.map { |key, value| [key.titleize, Article.consoles.key(value)] }) %> <br />

	          <p>Etat de la console</p>
            <div class="d-flex justify-content-between">
            <%= form.select :typeofgame, options_for_select(Article.typeofgames.map { |key, value| [key.titleize, Article.typeofgames.key(value)] }) %>
            
	    <%= form.submit "Rechercher", class:"btn btn-primary rounded-0" %>
    </div>

        <% end %>
      </div>
        </div>
        <div class="mb-3 d-none d-lg-block">
            
              <%= image_tag "game.png", style: "height: 300px;" %>
      </div>
      
      </section>

<section class="bg-mainos">
<div class="container ">
  <div class="row ">
    <p class="lead text-dark pt-5">Fil d'actu</p>
    <% @articles.each do |article| %>
    
      <% if article.buyer != nil %>
      <% elsif params.include?(:console) == false && params.include?(:typeofgame) == false %> <!-- Si y'a aucun filtre -->
        <%= render partial: "form/article/allarticle", locals: { article: article } %>
      <% elsif article.console == params[:console] || article.typeofgame == params[:typeofgame] %> <!-- Si y'a un filtre -->
        <%= render partial: "form/article/allarticle", locals: { article: article } %>
      <% end %>

    <% end %>
  </div>
</div>
</section>

app/views/articles/new.html.erb
<div class="bg-mainos2">
<h1 class="pt-5 pb-5 text-gradient text-dark text-center">Créer un nouvel article</h1>

<%= render "form/article/new", article: @article %>

<h5 class="pt-5 pb-5 text-gradient text-dark mb-0 text-center"> <%= link_to "Retour aux articles", articles_path %> </h5>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render "form/article/show" %>

<!-- ici la section des boutons modifier article/revenir/supprimer -->
<section>
  <div class="container py-0">
    <div class="d-flex align-items-center justify-content-center p-5 mb-4 bg-white rounded-0 border border-2 border-dark">
      <div class="container py-5">
        <h1 class="display-5 bg-dark text-white fw-bold border border-2 border-dark p-3 text-center"><%= @article.title %></h1>
        <p class="border border-2 border-dark p-3 text-dark"><%= @article.content %></p>
        <p><%= @article.console %> | <%= @article.typeofgame %></p>

      </div>
      <div class="container py-5 d-flex align-items-center justify-content-center d-none d-md-block">
        <%= image_tag("http://atlas-content-cdn.pixelsquid.com/stock-images/nintendo-nes-console-game-xwVG4NC-600.jpg", size: "200x300")%>
      </div>
    </div>

    <div class="row align-items-start justify-content-center">
      <% if current_user == @article.seller %>
        <div class="col-md-4">
          <div class="h-100 p-5 text-white bg-dark rounded-0 border border-2 border-dark d-flex row mb-4">
            <p class="lead text-white pb-3">Besoin de faire des modifications ?</p>
            <div class="text-center">
              
            <%= link_to "Modifier l'article", edit_article_path(@article), class:"btn btn-outline-secondary border-2 rounded-0" %>
          
          
            <%= button_to "Supprimer l'article", @article, method: :delete, class:"btn btn-secondary text-dark rounded-0" %>
          </div>
          </div>

        </div>
      <% else %>
        <div class="col-md-4">
          <div class="h-100 p-5 text-white bg-dark rounded-0 border border-2 border-dark d-flex row mb-4">
            <p class="lead text-white pb-3">Pensez à laisser un commentaire si vous aimez le produit :)</p>
            <% if current_user %>
<div class="commentaire d-none" >
<%= render partial: "thecomments/form",  locals: {article: @article} %>
</div>

<div class="d-flex justify-content-center container border border-2 border-dark mx-auto">
<%= link_to "Commenter", nil , remote: true, class: "btn btn-outline-secondary border-2 rounded-0", data: { controller: "comments", action: "comments#toggleForm"} %>
<% end %>
</div>
          </div>


        </div>
      <% end %>
      

      <div class="col-md-4">
        <div class="h-100 p-5 bg-white border rounded-0 border border-2 border-dark">

          <p class="lead fw-bold border-bottom border-2"><%= @article.price %> €</p>
          <p class="border-bottom border-2">
          Pour tout achat effectué par le biais du bouton "Payer", nous appliquons des frais couvrant notre protection acheteurs. Cette protection acheteurs comprend notre <%= link_to "Politique de remboursement", cgv_path %>.
          </p> 
          <p>
            Marque: <%= @article.console %>
          </p>
          <p>
            État: <%= @article.typeofgame %>  
          </p>
          <p class="border-bottom border-2">
            Paiement: VISA
          </p>
          <% if current_user %>
            <% if current_user != @article.seller %>
                <% if @artcartuser.class == NilClass %>
                  <%= button_to "Mettre dans le caddie", user_carts_path(current_user, article: @article.id), method: :create, class:"btn btn-primary rounded-0" %>
              <% else%>
                  <%= link_to "Mon panier", user_carts_path(current_user), class: "text-dark" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="bg-mainos">
  <div class="container ">
    <div class="row ">
      <p class="lead text-dark pt-5">Articles de ce vendeur</p>
      <div class="d-flex row">
        <% @articles.each do |article| %>
          <!-- Seul les articles vendu et dont le proprio est l'utilisateur de la page
          seront visibles-->
          <% if article.buyer == nil %>
                    <%= render partial: "form/article/exampleform", locals: { article: article } %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>