config/routes.rb
Rails.application.routes.draw do
  resources :thecomments
  resources :comments, only: [:create, :destroy, :update]
  resources :articles do
    resources :images, only: [:create, :destroy]
  end
  resources :orders, only: [:new, :create]
  resources :user do
    resources :carts, only: [:index, :create, :destroy]
    resources :avatars, only: [:create, :destroy]
  end
  devise_for :users
  resources :modifications, only: [:update]
  root to: "articles#index"
  get '/old', to: 'static_pages#old_skool_gaming'
  get '/kit', to: 'static_pages#kit_ui'
  get '/cgv', to: 'static_pages#cgv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  after_create :create_cart
  after_create :set_admin

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :my_articles, foreign_key: 'seller_id', class_name: "Article"
  has_many :my_purchases, foreign_key: 'buyer_id', class_name: "Article"
  has_one :cart
  has_many :comments
  has_many :orders
  has_many :thecomments


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def create_cart
    Cart.create(user: self, total: 0)
  end

  def set_admin

    if self.id == 1
    self.update(admin: true)
    end
  end
  
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :is_admin?, only: [:index]
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @thecomment = @user.thecomments.build
    @articles = @user.my_articles

  end

  def show_me
    @thecomment = @user.thecomments.build
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    if @user.admin == true
      @user.update(admin: false) 
    else 
      @user.update(admin: true)
    end
    redirect_to user_index_path
  end
  

  def is_admin?
    redirect_to root_path if current_user.admin == false
  end

  def destroy
    @user = User.find(params[:user_id])
    @user.cart.destroy
    @user.thecomments.destroy_all
    @user.my_articles.destroy_all
    @user.orders.destroy_all
    @user.destroy
    redirect_to user_index_path
  end

  def user_params
    params.require(:user)
  end


  
def user_params 
    params.require(:user).permit(:avatar)
end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/form/user/_alluser.html.erb
<div class="container bg-white mt-6 border border-2 border-dark">
  <div class="row">
    <div class="col-12">
      <table class="table table-flex">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Email</th>
            <th scope="col">Admin</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
        
          <tr>
            <% @user.each do |user| %>            
            <th scope="row"><%= user.id %></th>
            
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.admin %></td>
            <td>
            <div class= "d-flex justify-content space-between">
            <%= button_to " Powerrr", user_path(user, user_id: user.id), method: :put, class: "btn btn-sm bg-gradient-success " %>
            
            <%= button_to " Modifier l'utilisateur", edit_user_path(user), method: :get, class: "btn btn-sm bg-gradient-secondary " %>

            <%= button_to " Supprimer l'utilisateur", user_path(user, user_id: user.id), method: :delete, class: "btn btn-sm bg-gradient-danger " %>
            </div>
            </td>
          </tr>  
        <% end %>   
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/form/user/_edit.html.erb
<div class="container bg-white pt-5 pb-5 border border-2 border-dark rounded-0">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img pb-5">
                            <%if @user.avatar.attached?%> 
                                <%= image_tag @user.avatar, alt: 'avatar' %>
                            <% else %>
                            <img src="https://media.istockphoto.com/id/1307387607/vector/anonymous-vector-icon-incognito-sign-privacy-concept-human-head-with-glitch-face-personal.jpg?s=612x612&w=0&k=20&c=gABTCg7-xeCyeWDF-JnNzPbpnCeTX8wH-TxIYdkC0yQ=" alt=""/>
                            <% end %>
                            <div class="pt-3">
                            <%= form_with url: user_avatars_path(@user), multipart: true do |form| %> 
                                <%= form.file_field :avatar, class:"btn btn-outline-dark rounded-0 border-2" %>
                                <%= submit_tag "mettre à jour", class:"btn btn-primary rounded-0" %>
                            <% end %>
                            </div>
                        </div>
                        <%= form_with url: "/modifications/#{@user.id}", method: :patch do |form| %>
                    </div>

                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        <%= @user.first_name %> <%= @user.last_name %>
                                    </h5>
                                    <h6>
                                        <%= @user.email %>
                                    </h6>                                 
                            
                        </div>
                    </div>
                    <div class="col-md-2">
                        <%= form.submit "Editer", :class => "profile-edit-btn" %>
                    </div>
                </div>
                
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>ID User</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.id %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Prénom</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p> <%= @user.first_name%>
                                                <%= form.text_field :first_name, class:"form-control border-dark" %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Nom</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.last_name %>
                                                <%= form.text_field :last_name, class:"form-control border-dark"%></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Email</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.email %>
                                                <%= form.email_field :email, class:"form-control border-dark"%></p>
                                            </div>
                                        </div>                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Description</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.description %>
                                                <%= form.text_area :description, size: "30x3", class:"form-control border-dark" %> </p>
                                            </div>
                                            </div>
                                        </div>
                                          <div class="d-flex align-items-center">
                                        <%= form.submit "Modifier", :class => "btn btn-primary rounded-0" %>
                                    
                                    </div>       
                                </div>
                            
                            </div>
                        </div>
                    </div>
                </div>
            </div>           
        </div>
        <% end %>

app/views/form/user/_show.html.erb
<div class="container pt-5 pb-5 emp-profile border border-2 border-dark rounded-0">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img pb-5">
                            <%if @user.avatar.attached?%> 
                                <%= image_tag @user.avatar, alt: 'avatar' %>
                            <% else %>
                            <img src="https://media.istockphoto.com/id/1307387607/vector/anonymous-vector-icon-incognito-sign-privacy-concept-human-head-with-glitch-face-personal.jpg?s=612x612&w=0&k=20&c=gABTCg7-xeCyeWDF-JnNzPbpnCeTX8wH-TxIYdkC0yQ=" width= "10px" height="10px" alt="logo"/>
                            <% end %>
                        </div>
                     
                    </div>
                    
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        <%= @user.first_name %> <%= @user.last_name %>
                                    </h5>
                                    <h6>
                                        <%= @user.email %>
                                    </h6>                                                              
                        </div>
                    </div>
                    <div class="col-md-2">
                        <%= link_to "Editer", edit_user_path(@user), class: "profile-edit-btn" %>
                    </div>
                </div>
                
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>ID User</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.id %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Prénom</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.first_name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Nom</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.last_name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Email</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.email %></p>
                                            </div>
                                        </div>                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>Description</p>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.description %></p>
                                            </div>
                                        </div>
                                </div>
                            
                            </div>
                        </div>
                    </div>
                </div>
            </div>           
        </div>