config/routes.rb
Rails.application.routes.draw do
  resources :thecomments
  resources :comments, only: [:create, :destroy, :update]
  resources :articles do
    resources :images, only: [:create, :destroy]
  end
  resources :orders, only: [:new, :create]
  resources :user do
    resources :carts, only: [:index, :create, :destroy]
    resources :avatars, only: [:create, :destroy]
  end
  devise_for :users
  resources :modifications, only: [:update]
  root to: "articles#index"
  get '/old', to: 'static_pages#old_skool_gaming'
  get '/kit', to: 'static_pages#kit_ui'
  get '/cgv', to: 'static_pages#cgv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/thecomment.rb
class Thecomment < ApplicationRecord
	  
	belongs_to :user
	belongs_to :article
end

app/controllers/thecomments_controller.rb
class ThecommentsController < ApplicationController
  before_action :set_thecomment, only: %i[ show edit update destroy ]

  # GET /thecomments or /thecomments.json
  def index
    @thecomments = Thecomment.all
  end

  # GET /thecomments/1 or /thecomments/1.json
  def show
  end

  # GET /thecomments/new
  def new
    @thecomment = Thecomment.new
  end

  # GET /thecomments/1/edit
  def edit
  end

  # POST /thecomments or /thecomments.json
  def create
    @thecomment = Thecomment.new
    @thecomment.title = params[:title]
    @thecomment.text = params[:text]
    @thecomment.user = current_user
    @thecomment.article_id = params[:article_id]

    respond_to do |format|
      if @thecomment.save
        format.html { redirect_to article_path(params[:article_id]), notice: "Thecomment was successfully created." }
        format.json { render :show, status: :created, location: @thecomment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thecomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thecomments/1 or /thecomments/1.json
  def update
    respond_to do |format|
      if @thecomment.update(thecomment_params)
        format.html { redirect_to thecomment_url(@thecomment), notice: "Thecomment was successfully updated." }
        format.json { render :show, status: :ok, location: @thecomment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thecomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thecomments/1 or /thecomments/1.json
  def destroy
    @thecomment.destroy

    respond_to do |format|
      format.html { redirect_to thecomments_url, notice: "Thecomment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thecomment
      @thecomment = Thecomment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thecomment_params
      params.require(:thecomment).permit(:user_id, :text, :title)
    end
end

app/helpers/thecomments_helper.rb
module ThecommentsHelper
end

app/views/thecomments/_form.html.erb
  <div class="align-items-center justify-content-center container d-flex flex-row bg-white pt-3 pb-3 border border-2 border-dark card-box mb-3">
  <%= form_with url: thecomments_path do |form| %>
    
   <%= form.hidden_field :article_id, :value => article.id %>
   <%= form.hidden_field :user_id, :value => current_user.id %>
<div>
   <p class="text-dark">Titre</p>
   <%= form.text_area :title, class:"form-control" %>
</div>
<div>
    <p class="pt-2 text-dark">Commentaire</p>
   <%= form.text_area :text, class:"form-control" %>
</div>

   <div class="actions pt-2">
    <%= form.submit"Envoyer", class:"btn btn-primary rounded-0" %>
   </div>
     <% end %>
</div>

app/views/thecomments/_thecomment.html.erb
<div id="<%= dom_id thecomment %>">
</div>

app/views/thecomments/edit.html.erb
<h1>Editing thecomment</h1>

<%= render "form", thecomment: @thecomment %>

<br>

<div>
  <%= link_to "Show this thecomment", @thecomment %> |
  <%= link_to "Back to thecomments", thecomments_path %>
</div>

app/views/thecomments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Thecomments</h1>

<div id="thecomments">
  <% @thecomments.each do |thecomment| %>
    <%= render thecomment %>
    <p>
      <%= link_to "Show this thecomment", thecomment %>
    </p>
  <% end %>
</div>

<%= link_to "New thecomment", new_thecomment_path %>

app/views/thecomments/new.html.erb
<h1>New thecomment</h1>

<%= render "form", thecomment: @thecomment %>

<br>

<div>
  <%= link_to "Back to thecomments", thecomments_path %>
</div>

app/views/thecomments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thecomment %>

<div>
  <%= link_to "Edit this thecomment", edit_thecomment_path(@thecomment) %> |
  <%= link_to "Back to thecomments", thecomments_path %>

  <%= button_to "Destroy this thecomment", @thecomment, method: :delete %>
</div>